// src/core/constants/serviceTokens.ts
// Service tokens for dependency injection

export const SERVICE_TOKENS = {
  // User repositories
  USER_REPOSITORY: 'USER_REPOSITORY',
  MOCK_USER_REPOSITORY: 'MOCK_USER_REPOSITORY',
  INDEXED_DB_REPOSITORY: 'INDEXED_DB_REPOSITORY',

  // Identity services
  IDENTITY_SERVICE: 'IDENTITY_SERVICE',
  MOCK_IDENTITY_SERVICE: 'MOCK_IDENTITY_SERVICE',

  // Token providers
  TOKEN_PROVIDER: 'TOKEN_PROVIDER',
  JWT_TOKEN_PROVIDER: 'JWT_TOKEN_PROVIDER',

  // Encryption engines
  ENCRYPTION_ENGINE: 'ENCRYPTION_ENGINE',
  BCRYPT_ENCRYPTION: 'BCRYPT_ENCRYPTION',

  // Storage services
  STORAGE_SERVICE: 'STORAGE_SERVICE',
  LOCAL_STORAGE_SERVICE: 'LOCAL_STORAGE_SERVICE',
  COOKIE_STORAGE_SERVICE: 'COOKIE_STORAGE_SERVICE',

  // Key managers
  KEY_MANAGER: 'KEY_MANAGER',
  RSA_KEY_MANAGER: 'RSA_KEY_MANAGER',
} as const;
